# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://tegge:8e39dd6378b86a09ba3b7da12a203d85766b5ecc@github.ibm.com/watson-health-fhir-server/ig-common-data-model.git"
        backup-ssh: "git@github.ibm.com:watson-health-fhir-server/ig-common-data-model.git"
        source_branch: "gh-pages"
        destination_branch: "gh-pages"
        github_token: ${{ secrets.PAT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
